services:

  php-fpm:
    build:
      context: ./containers/dev
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
        NPM_MIRROR: ${NPM_MIRROR:-https://registry.npmjs.org/}
    volumes:
      - ../apiato:/var/www/back
      - ./containers/dev/logs/php-commandhistory:/commandhistory
    user: root:root
    command: bash -cl "php-fpm"
    working_dir: /var/www/back
    depends_on:
      - pgsql
      - mysql
    restart: unless-stopped

  pgsql:
    image: postgres:16.3-bookworm
    volumes:
      - ./containers/pgsql/databases:/var/lib/postgresql/data
    ports:
      - ${PSQL_FORWARD_PORT:-54321}:5432
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE:-AgileForge}
      POSTGRES_USER: ${DB_USERNAME:-AgileForge}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-AgileForge}
      PGDATA: /var/lib/postgresql/data/AgileForge
    restart: unless-stopped

  mysql:
    image: mysql:8.4.0
    volumes:
      - ./containers/mysql/databases:/var/lib/mysql
    ports:
      - ${MYSQL_FORWARD_PORT:-33061}:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-AgileForge}
      MYSQL_USER: ${DB_USERNAME:-AgileForge}
      MYSQL_PASSWORD: ${DB_PASSWORD:-AgileForge}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-AgileForge}
    restart: unless-stopped

  nginx:
    build:
      context: ./containers/nginx
      args:
        APP_HOST: ${APP_HOST:-agile-forge.lc}
    volumes:
      - ../apiato:/var/www/back
    ports:
      - ${PORT_NGINX:-80}:80
    depends_on:
      - php-fpm
    restart: unless-stopped
